apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::904223757046:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::904223757046:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FNYJ3A0E33V3
      username: system:node:{{EC2PrivateDNSName}}

kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-06T22:35:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1431"
  uid: 9410a931-b4a2-44d2-abd1-2d95753ad90e
